### ISSUE TITLE
Nagios Core 4.2.0 does a Bus error on startup on FreeBSD

### ISSUE THREAD

**Issue by mat813** [NagiosEnterprises/nagioscore#155]
This is trying to run with the sample configuration distributed with the nagios core distribution.

```
root@10amd64-ports:/usr/ports/net-mgmt/nagios4 # gdb /usr/local/bin/nagios
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) run -v /usr/local/etc/nagios/nagios.cfg
Starting program: /usr/local/bin/nagios -v /usr/local/etc/nagios/nagios.cfg

Nagios Core 4.2.0
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 08-01-2016
License: GPL

Website: https://www.nagios.org
Reading configuration data...
   Read main config file okay...

Program received signal SIGBUS, Bus error.
0x00000000004b1bfd in dkhash_get_bucket (t=0x80184e340, key=0x801819140 "admins", slot=2) at dkhash.c:85
85                      if (!strcmp(key, bkt->key))
Current language:  auto; currently minimal
(gdb) bt
#0  0x00000000004b1bfd in dkhash_get_bucket (t=0x80184e340, key=0x801819140 "admins", slot=2) at dkhash.c:85
#1  0x00000000004b198f in dkhash_insert (t=0x80184e340, k1=0x801819140 "admins", k2=0x0, data=0x8018060d0) at dkhash.c:113
#2  0x0000000000472929 in add_contactgroup (name=0x801819140 "admins", alias=0x801807f20 "Nagios Administrators") at ../common/objects.c:1351
#3  0x000000000049eee0 in xodtemplate_register_contactgroup (this_contactgroup=0x801878080) at ../xdata/xodtemplate.c:7366
#4  0x00000000004817e4 in xodtemplate_register_objects () at ../xdata/xodtemplate.c:7037
#5  0x000000000047bda7 in xodtemplate_read_config_data (main_config_file=0x8018060a0 "/usr/local/etc/nagios/nagios.cfg", options=32511) at ../xdata/xodtemplate.c:444
#6  0x000000000046e633 in read_object_config_data (main_config_file=0x8018060a0 "/usr/local/etc/nagios/nagios.cfg", options=32511) at ../common/objects.c:272
#7  0x000000000042c07d in read_all_object_data (main_config_file=0x8018060a0 "/usr/local/etc/nagios/nagios.cfg") at config.c:70
#8  0x0000000000415a4b in main (argc=3, argv=0x7fffffffeb20) at nagios.c:451
```

I've had a look at it, it tries to use a slot that is not initialized, and it doesn't go well:

```
(gdb) p key
$1 = 0x801819140 "admins"
(gdb) p bkt->key
Error accessing memory address 0x73735f6b63656863: Bad address.
(gdb) p bkt
$2 = (dkhash_bucket *) 0x73735f6b63656863
(gdb) p slot
$3 = 2
(gdb) p t->num_buckets
$4 = 2
```

**Comment by darylrichards** [comment]
This is fixed by #154 even though it doesn't list that. I manually did that in my FreeBSD build and away it goes..

**Comment by darylrichards** [comment]
Maybe someday I'll learn more about github..

I mean to say, fixed in [ac0a96f]

**Comment by mat813** [comment]
Will there be a new release soon ? Or should I use 4.2.0 with this patch in the mean time ?

**Comment by jfrickson** [comment]
@mat813 I'm planning a bug-fix release right around September 1. So you can patch now, or wait a week. Either way.

Closing the issue now. It can be reopened if necessary. More comments welcome.
